import type { Metadata } from "next";
import { Domine, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
// import HomePage from "./components/HomePage";
// import LoadingWrapper from "./components/LoadingWrapper";
import { NavContextProvider } from "./components/NavContextProvider";
// import LoadingWrapper from "./components/LoadingWrapper";
import Navbar from "./components/Navbar";

const domine = Domine({
  variable: "--gfont-domine",
  subsets: ["latin"],
});

const ibm = IBM_Plex_Sans({
  variable: "--gfont-ibm",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Snehil Kakani",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${domine.variable} ${ibm.variable} antialiased overflow-x-hidden h-[1000vh] bg-background`}
      >
        <NavContextProvider>
          <Navbar />
          {children}
        </NavContextProvider>
      </body>
    </html>
  );
}
