const featPhotos: {
  image: string;
  exp: string;
  shutter: string;
  aperture: string;
  iso: number;
  alt: string;
  isBig?: boolean;
}[] = [
  {
    image: "/photos/yosemite_bridalveil.jpg",
    exp: "+0.7",
    shutter: "1/1000",
    aperture: "3.2",
    iso: 400,
    alt: "Bridalveil Falls in Yosemite National Park",
    isBig: false,
  },
  {
    image: "/photos/cloudy_sunset.jpg",
    exp: "+0",
    iso: 100,
    shutter: "1/40",
    aperture: "5.6",
    alt: "A cloudy sunset near my house",
    isBig: false,
  },
  {
    image: "/photos/ollie.jpg",
    isBig: true,
    exp: "+0.3",
    shutter: "1/60",
    aperture: "5",
    iso: 4000,
    alt: "Picture of my dog Ollie",
  },
  {
    image: "/photos/yosemite.jpg",
    exp: "-1.0",
    shutter: "1/2000",
    aperture: "9",
    iso: 500,
    alt: "Yosemite Valley viewpoint",
    isBig: false,
  },
  // {
  //   image: "/photos/firework1.jpg",
  //   isBig: false,
  //   exp: "+0",
  //   shutter: "6.0",
  //   aperture: "18",
  //   iso: 1250,
  //   alt: "Fireworks display during 4th of July celebrations",
  // },
  {
    image: "/photos/decs.jpg",
    exp: "+0",
    shutter: "1/60",
    aperture: "3.5",
    iso: 400,
    alt: "Homecoming decorations meeting",
    isBig: false,
  },
  {
    image: "/photos/ny_rc.jpg",
    exp: "+0",
    shutter: "1/40",
    aperture: "4",
    iso: 1600,
    alt: "The Radio City Music Hall in New York City",
    isBig: true,
  },
  // {
  //   image: "/photos/yosemite2.jpg",
  //   exp: "+0",
  //   shutter: "1/160",
  //   aperture: "22",
  //   iso: 320,
  //   alt: "A mountain view in Yosemite National Park",
  //   isBig: false,
  // },
  {
    image: "/photos/grad_party.jpg",
    exp: "0",
    shutter: "1/60",
    aperture: "4",
    iso: 400,
    alt: "Yearbooks and grad caps at a graduation party with friends",
    isBig: false,
  },
  {
    image: "/photos/ny_stop.jpg",
    exp: "+0",
    shutter: "1/80",
    aperture: "3.5",
    iso: 100,
    isBig: false,
    alt: "A pedestrian stop sign in New York City",
  },

  {
    image: "/photos/firework2.jpg",
    isBig: true,
    exp: "+0",
    shutter: "1/2",
    aperture: "4.8",
    iso: 500,
    alt: "Fireworks display during 4th of July celebrations",
  },
  // {
  //   image: "/photos/sunset.jpg",
  //   isBig: false,
  //   exp: "+0",
  //   aperture: "13",
  //   shutter: "1/125",
  //   iso: 500,
  //   alt: "Sunset near my house",
  // },
  {
    image: "/photos/grill.jpg",
    isBig: false,
    exp: "+0",
    shutter: "1/60",
    aperture: "4",
    iso: 400,
    alt: "A cookout in the park with burgers and hot dogs",
  },
  {
    image: "/photos/yosemite_camp_curry.jpg",
    isBig: false,
    exp: "-0.7",
    shutter: "1/15",
    aperture: "2.8",
    iso: 1600,
    alt: "Camp Curry sign in Curry Village, Yosemite National Park",
  },
  {
    image: "/photos/vinyl_player.jpg",
    isBig: true,
    exp: "+0",
    shutter: "1/60",
    aperture: "4",
    iso: 400,
    alt: "A vinyl player with a record playing",
  },
  {
    image: "/photos/improv.jpg",
    isBig: false,
    exp: "+0",
    shutter: "1/640",
    aperture: "4",
    iso: 100,
    alt: "Improv team practicing in the local park",
  },
  {
    image: "/photos/ny_fountain.jpg",
    isBig: false,
    exp: "+0",
    shutter: "1/800",
    aperture: "3.5",
    iso: 100,
    alt: "A fountain in Washington Square Park, New York City",
  },
  {
    image: "/photos/tompkins.jpg",
    isBig: true,
    exp: "+0.7",
    shutter: "1/950",
    aperture: "5.6",
    iso: 500,
    alt: "Tompkins Drive in San Jose, California",
  },
  {
    image: "/photos/ny_flag.jpg",
    isBig: false,
    exp: "+0",
    shutter: "1/6",
    aperture: "3.5",
    iso: 400,
    alt: "A flag in New York City",
  },
  {
    image: "/photos/yosemite_meadow.jpg",
    isBig: false,
    exp: "+0.3",
    shutter: "1/1000",
    aperture: "3.8",
    iso: 500,
    alt: "Cook's Meadow in Yosemite National Park",
  },
  // {
  //   image: "/photos/yosemite_reservoir.jpg",
  //   isBig: true,
  //   exp: "+1.0",
  //   shutter: "1/1250",
  //   aperture: "6.4",
  //   iso: 500,
  //   alt: "A reservoir near Yosemite National Park",
  // },
  {
    image: "/photos/ny_bridge.jpg",
    isBig: true,
    exp: "+0",
    shutter: "1/200",
    aperture: "8",
    iso: 100,
    alt: "Manhattan Bridge in New York City",
  },
  // {
  //   image: "/photos/yosemite_v_falls.jpg",
  //   isBig: false,
  //   exp: "+0",
  //   shutter: "1/1500",
  //   aperture: "7.1",
  //   iso: 640,
  //   alt: "An overhead view of Vernal Falls in Yosemite National Park",
  // },
  {
    image: "/photos/ny_deer.jpg",
    isBig: false,
    exp: "+0",
    shutter: "1/200",
    aperture: "4.5",
    iso: 100,
    alt: "A deer in the Bronx Zoo, New York City",
  },
  {
    image: "/photos/yosemite_road.jpg",
    isBig: false,
    exp: "+0",
    shutter: "1/125",
    aperture: "4.5",
    iso: 500,
    alt: "A road in Yosemite National Park",
  },
  {
    image: "/photos/yosemite_sunset.jpg",
    isBig: true,
    exp: "-1.0",
    shutter: "1/125",
    aperture: "11",
    iso: 1250,
    alt: "Glacier Point in Yosemite National Park",
  },
];

export default featPhotos;